import { useState } from 'react';
import { emptyJourney } from '../tracking.js';

export default function JourneyForm({ match, resident, event, onSave, onCancel }) {
  const [journey, setJourney] = useState({ ...emptyJourney, ...match.journey });
  const change = ({ target }) => setJourney(current => ({ ...current, [target.name]: target.value }));
  const submit = formEvent => { formEvent.preventDefault(); onSave(journey); };

  return <form className="journey-form" onSubmit={submit}><div className="journey-form-context"><span className={`resident-avatar ${resident.color}`}>{resident.initials}</span><div><strong>{resident.first_name}</strong><small>{event.title}</small></div></div><div className="form-grid">
    <label className="field field-wide"><span>Participation</span><select name="participation" value={journey.participation} onChange={change}><option value="pending">À confirmer</option><option value="participated">Participation réalisée</option><option value="not_participated">Participation non réalisée</option></select></label><label className="field field-wide"><span>Prochaine étape</span><select name="nextStep" value={journey.nextStep} onChange={change}><option value="none">Aucune pour le moment</option><option value="training">Formation</option><option value="interview">Entretien</option><option value="job">Emploi ou mission</option><option value="project">Projet personnel</option><option value="network">Mise en réseau</option></select></label>
    <label className="field field-wide"><span>Compétence développée</span><input name="skills" value={journey.skills} onChange={change} placeholder="Ex. prise de parole, cuisine collective…" /></label><label className="field field-wide"><span>Contact ou lien créé</span><input name="contact" value={journey.contact} onChange={change} placeholder="Sans donnée personnelle inutile" /></label>
    <label className="field field-wide"><span>Suivi à 30 jours</span><select name="followUp30" value={journey.followUp30} onChange={change}><option value="pending">À réaliser</option><option value="positive">Progression confirmée</option><option value="no_change">Pas de changement observé</option><option value="unreachable">Pas encore de réponse</option></select></label><label className="field field-wide"><span>Suivi à 90 jours</span><select name="followUp90" value={journey.followUp90} onChange={change}><option value="pending">À réaliser</option><option value="positive">Progression confirmée</option><option value="no_change">Pas de changement observé</option><option value="unreachable">Pas encore de réponse</option></select></label>
    <label className="field field-full"><span>Notes factuelles</span><textarea name="notes" rows="3" value={journey.notes} onChange={change} placeholder="Faits observés et prochaine action, sans appréciation personnelle." /></label></div><div className="form-actions"><button type="button" className="button button-quiet" onClick={onCancel}>Annuler</button><button className="button button-dark">Enregistrer le suivi</button></div></form>;
}
